name: origen-theme
type: wordpress
docroot: wordpress
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - PHP_DISPLAY_ERRORS=Off
  - PHP_ERROR_REPORTING=E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
corepack_enable: false
upload_dirs: "content/uploads"
hooks:
  post-composer:
    - exec: wp core config --dbname=db --dbuser=db --dbpass=db --dbhost=db --skip-check --path=wordpress
    - exec: wp core install --url="${DDEV_PRIMARY_URL}" --title="Origen Theme Site" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --path=wordpress
  post-start:
    - exec: echo "define('WP_DEBUG_DISPLAY', false); @ini_set('display_errors', 0);" >> wordpress/wp-config.php
disable_settings_management: true