name: origen-theme
type: wordpress
docroot: ""
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
hooks:
    post-composer:
        - exec: wp core config --dbname=db --dbuser=db --dbpass=db --dbhost=db --skip-check --path=wordpress
        - exec: wp core install --url="${DDEV_PRIMARY_URL}" --title="Origen Theme Site" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --path=wordpress
upload_dirs:
    - content/uploads
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment: []
corepack_enable: false
